version: "3.8"
services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: samindia
      MARIADB_DATABASE: Python_DE
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: