services:
  db:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: samindia
      MARIADB_DATABASE: Python_DE
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: samindia
      MONGO_INITDB_DATABASE: PythonDE

    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
