services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: samindia
      MARIADB_DATABASE: Python_DE
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql